name: ESLint and Terraform Verify

on:
    # workflow_dispatch:

    push:
        branches: ["main"]
        paths: ['dockerize-sample-app/**']

    pull_request:
        branches: ["main"]
        paths: ['dockerize-sample-app/**']

jobs:
    eslint:
        name: Code Lint scanning
        runs-on: ubuntu-latest

        steps:
          - name: Repository checkout
            uses: actions/checkout@v3

          - name: Configure Node Runtime
            uses: actions/setup-node@v2
            with:
                node-version: '20'
        
          - name: Fulfill dependencies
            working-directory: ./dockerize-sample-app/
            run: npm install

          - name: Run ESLint
            working-directory: ./dockerize-sample-app/
            run: npx eslint .
                 --config .eslintrc.cjs  
                 --ext .js,.jsx,.ts,.tsx
            continue-on-error: false

    verify:
      runs-on: ubuntu-latest

      steps: 
        - name: Repository checkout
          uses: actions/checkout@v3

        - name: Configure Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform-version: 1.4.0

        - name: Terraform FMT
          working-directory: ./dockerize-sample-app/terraform
          run: terraform fmt -check -recursive  